version: '3.8'

services:
  streamlit-app:
    build:
      context: .
      dockerfile: Dockerfile.streamlit
    ports:
      - "8501:8501"
    volumes:
      - ./models:/app/models:ro
      - ./data:/app/data:ro
    environment:
      - PYTHONPATH=/app
    restart: unless-stopped
    networks:
      - titanic-network

  fastapi-app:
    build:
      context: .
      dockerfile: Dockerfile.fastapi
    ports:
      - "8000:8000"
    volumes:
      - ./models:/app/models:ro
      - ./data:/app/data:ro
    environment:
      - PYTHONPATH=/app
    restart: unless-stopped
    networks:
      - titanic-network

networks:
  titanic-network:
    driver: bridge